export default [
    't*eo',
    "J'arrive un peu plus tard",
    'Htéo',
    'Téoh',
    'Mais il y a un H 😜',
    'mdr ça a même plus de sens ça',
    'https://images-ext-2.discordapp.net/external/I0VdJmPpO9VRfdbcbI4j2R1avelXLcxzFz6NqiPEnSg/https/media.tenor.com/meLXiGBtzXgAAAPo/incroyable.mp4',
    'meurt pourriture communiste',
    'La corruption a été si facile',
    'téo',
    'Téo se Téo surtout',
    'Nostalgique ce teo',
    'Ce soir raft pour ceux qui veulent nous rejoindre',
    "Je l'utiliserai a un moment impromptu",
    'Ton fond de webcam un vendredi',
    'La corruption a été si facile',
    'https://images-ext-1.discordapp.net/external/2mxNq3mqCvSzBIOWlEe2QhrYEJ9slN0GfJJ3sJRR2vU/https/media.tenor.com/uBr8BS_BD5QAAAPo/theo-tweetpark.mp4',
    'https://images-ext-1.discordapp.net/external/s09CM84U07rag6-int43u35SRCGU9qK2yuikd9uP_Ns/https/media.tenor.com/tq4Foo72P-MAAAPo/theo-theo-hernandez.mp4',
];
