export default [
    '🍵🪓🇪💦',
    'Téhaut',
    'théheau',
    'theau',
    ':tea: :ocean:',
    ':tea: :sweat_drops:',
    ':tea: :ocean:',
    '🍵 🌊',
    '🍵 💦',
    '🍵 🚰',
    '🍵 💧',
    'Taie haut',
    't h e o',
    'T🪓eo',
    'T :axe: eo',
    'hello :regional_indicator_t::regional_indicator_h: :regional_indicator_e::regional_indicator_o:',
];
