export default [
    'Շђé๏',
    'ȶɦéօ',
    'ƬΉéӨ',
    '𝒯𝓗𝓔𝓞',
    '丅卄éo',
    'ƚԋéσ',
    'ttTthéééèèèhéhéhéhhohohohoho',
    "salut théo sa va ? j'ai une thèorie pour toi",
    'T(-)eo',
    'T|-|eo',
    'The∅',
    'T|-|eo',
    'T:regional_indicator_h:eo',
    't`heo',
    'bon ok tu peux écrire 1x théo sans suppr',
    "Mais tu vois mon gros théo c'est qu'une théorie",
    'theheheheho',
    'thhheo',
    'théo',
    'Théo',
    'the0',
    't.h.e.o',
    'théorie théo théorie théorie théorie théorie théorie théorie',
    'je devrais faire un bot discord qui supprime tous les messages avec "théo"',
];
