export default [
    ['tehaut', 'theo'],
    ['tehau', 'theo'],
    ['🍵', 'the'],
    ['🌊', 'o'],
    ['💦', 'o'],
    ['💧', 'o'],
    ['🚰', 'o'],
    ['🧊', 'o'],
    ['🪓', 'h'],
    ['aut', 'o'],
    ['au', 'o'],
    ['⬆', 'o'],
    ['↑', 'o'],
    ['^', 'o'],
    ['˄', 'o'],
    ['☝', 'o'],
    [':point_up:', 'o'],
    [':tea:', 'the'],
    [':ocean:', 'o'],
    [':sweat_drops:', 'o'],
    [':potable_water:', 'o'],
    [':axe:', 'h'],
    ['theheo', 'theo'],
];
