export default [
    ['T(-)eo', 1],
    ['Taie haut', 1],
    ['T|-|eo', 1],
    ['The∅', 1],
    ['🍵 💧', 1],
    ['T|-|eo', 1],
    ['T🪓eo', 1],
    ['Htéo', 1],
    ['Téoh', 1],
    ['mdr ça a même plus de sens ça', 0],
    ['Mais il y a un H 😜', 0],
    ['théheau', 1],
    ['theau', 1],
    ['Thaut', 0],
    ['Téhaut', 1],
    ['TTThèhèhèhèhèhèhéhéhéhé0', 1],
    ['T:regional_indicator_h:eo', 1],
    [
        'hello :regional_indicator_t::regional_indicator_h: :regional_indicator_e::regional_indicator_o:',
        1,
    ],
    ['t`heo', 1],
    ['bon ok tu peux écrire 1x théo sans suppr', 1],
    [
        'je devrais faire un bot discord qui supprime tous les messages avec "théo"',
        1,
    ],
    [
        'https://images-ext-1.discordapp.net/external/2mxNq3mqCvSzBIOWlEe2QhrYEJ9slN0GfJJ3sJRR2vU/https/media.tenor.com/uBr8BS_BD5QAAAPo/theo-tweetpark.mp4',
        1,
    ],
    [
        'https://images-ext-1.discordapp.net/external/s09CM84U07rag6-int43u35SRCGU9qK2yuikd9uP_Ns/https/media.tenor.com/tq4Foo72P-MAAAPo/theo-theo-hernandez.mp4',
        1,
    ],
    ['théorie  théorie théorie théorie théorie théorie théorie', 2],
    ['théorie théo théorie théorie théorie théorie théorie théorie', 1],
    ['téo', 0],
    ['Téo se Téo surtout', 0],
    ['Nostalgique ce teo', 0],
    ['Ce soir raft pour ceux qui veulent nous rejoindre', 0],
    ["Je l'utiliserai a un moment impromptu", 0],
    ['Ton fond de webcam un vendredi', 0],
    ['La corruption a été si facile', 0],
    ['meurt pourriture communiste', 0],
    [
        'https://images-ext-2.discordapp.net/external/I0VdJmPpO9VRfdbcbI4j2R1avelXLcxzFz6NqiPEnSg/https/media.tenor.com/meLXiGBtzXgAAAPo/incroyable.mp4',
        0,
    ],
    ["Mais tu vois mon gros théo c'est qu'une théorie", 1],
    ['théorie', 2],
    ['theheheheho', 1],
    ['thhheo', 1],
    ['théo', 1],
    ['teo', 0],
    ['Théo', 1],
    ['the0', 1],
    ['t.h.e.o', 1],
    ['t*eo', 1],
    ['', 0],
    ['Petite séance d\'osthéopathie avec Mr. Bra de son prénom Ken', 0]
];
