import { AnswerType } from '../answer';

export default [
    ["salut théo sa va ? j'ai une thèorie pour toi", AnswerType.Violation],
    ['', -1],
    ["J'arrive un peu plus tard", AnswerType.None],
    ['T(-)eo', AnswerType.Violation],
    ['Taie haut', AnswerType.Violation],
    ['T|-|eo', AnswerType.Violation],
    ['The∅', AnswerType.Violation],
    ['🍵 💧', AnswerType.Violation],
    ['T|-|eo', AnswerType.Violation],
    ['T🪓eo', AnswerType.Violation],
    ['Htéo', AnswerType.Violation],
    ['Téoh', AnswerType.Violation],
    ['mdr ça a même plus de sens ça', AnswerType.None],
    ['Mais il y a un H 😜', AnswerType.None],
    ['théheau', AnswerType.Violation],
    ['theau', AnswerType.Violation],
    ['Thaut', AnswerType.None],
    ['Téhaut', AnswerType.Violation],
    ['TTThèhèhèhèhèhèhéhéhéhé0', AnswerType.Violation],
    ['T:regional_indicator_h:eo', AnswerType.Violation],
    [
        'hello :regional_indicator_t::regional_indicator_h: :regional_indicator_e::regional_indicator_o:',
        1,
    ],
    ['t`heo', AnswerType.Violation],
    ['bon ok tu peux écrire 1x théo sans suppr', AnswerType.Violation],
    [
        'je devrais faire un bot discord qui supprime tous les messages avec "théo"',
        AnswerType.Violation,
    ],
    [
        'https://images-ext-1.discordapp.net/external/2mxNq3mqCvSzBIOWlEe2QhrYEJ9slN0GfJJ3sJRR2vU/https/media.tenor.com/uBr8BS_BD5QAAAPo/theo-tweetpark.mp4',
        AnswerType.Violation,
    ],
    [
        'https://images-ext-1.discordapp.net/external/s09CM84U07rag6-int43u35SRCGU9qK2yuikd9uP_Ns/https/media.tenor.com/tq4Foo72P-MAAAPo/theo-theo-hernandez.mp4',
        AnswerType.Violation,
    ],
    [
        'théorie théo théorie théorie théorie théorie théorie théorie',
        AnswerType.Violation,
    ],
    ['téo', AnswerType.None],
    ['Téo se Téo surtout', AnswerType.None],
    ['Nostalgique ce teo', AnswerType.None],
    ['Ce soir raft pour ceux qui veulent nous rejoindre', AnswerType.None],
    ["Je l'utiliserai a un moment impromptu", AnswerType.None],
    ['Ton fond de webcam un vendredi', AnswerType.None],
    ['La corruption a été si facile', AnswerType.None],
    ['meurt pourriture communiste', AnswerType.None],
    [
        'https://images-ext-2.discordapp.net/external/I0VdJmPpO9VRfdbcbI4j2R1avelXLcxzFz6NqiPEnSg/https/media.tenor.com/meLXiGBtzXgAAAPo/incroyable.mp4',
        AnswerType.None,
    ],
    ["Mais tu vois mon gros théo c'est qu'une théorie", AnswerType.Violation],
    ['theheheheho', AnswerType.Violation],
    ['thhheo', AnswerType.Violation],
    ['théo', AnswerType.Violation],
    ['teo', AnswerType.None],
    ['Théo', AnswerType.Violation],
    ['the0', AnswerType.Violation],
    ['t.h.e.o', AnswerType.Violation],
    ['t*eo', AnswerType.Violation],
    ['', AnswerType.None],
    [
        "Petite séance d'osthéopathie avec Mr. Bra de son prénom Ken",
        AnswerType.None,
    ],
];
