import { AnswerType } from '../answer';

export default [
    ['<@1186434212983746712> test', AnswerType.Provocation],
    ['', -1],
    ['Téhaut', AnswerType.Trick],
    ['théheau', AnswerType.Trick],
    ['theau', AnswerType.Trick],
    ['Շђé๏', AnswerType.Violation],
    ['ȶɦéօ', AnswerType.Violation],
    ['ƬΉéӨ', AnswerType.Violation],
    ['𝒯𝓗𝓔𝓞', AnswerType.Violation],
    ['gautheo', AnswerType.Correction],
    ['丅卄éo', AnswerType.Violation],
    ['ƚԋéσ', AnswerType.Violation],
    [':tea: :ocean:', AnswerType.Trick],
    [':tea: :sweat_drops:', AnswerType.Trick],
    [':tea: :ocean:', AnswerType.Trick],
    ['🍵 🌊', AnswerType.Trick],
    ['🍵 💦', AnswerType.Trick],
    ['🍵 🚰', AnswerType.Trick],
    ['t*eo', AnswerType.None],
    ['ttTthéééèèèhéhéhéhhohohohoho', AnswerType.Violation],
    ['🍵 💧', AnswerType.Trick],
    [
        'je devrais faire un bot discord qui supprime tous les messages avec "théo"',
        AnswerType.Violation,
    ],
    ['Taie haut', AnswerType.Trick],
    ["salut théo sa va ? j'ai une thèorie pour toi", AnswerType.Violation],
    ['t h e o', AnswerType.Trick],
    ["J'arrive un peu plus tard", AnswerType.None],
    ['T(-)eo', AnswerType.Violation],
    ['T|-|eo', AnswerType.Violation],
    ['The∅', AnswerType.Violation],
    ['T|-|eo', AnswerType.Violation],
    ['T🪓eo', AnswerType.Trick],
    ['T :axe: eo', AnswerType.Trick],
    ['Htéo', AnswerType.None],
    ['Téoh', AnswerType.None],
    ['mdr ça a même plus de sens ça', AnswerType.None],
    ['Mais il y a un H 😜', AnswerType.None],

    ['Thaut', AnswerType.None],
    ['T:regional_indicator_h:eo', AnswerType.Violation],
    [
        'hello :regional_indicator_t::regional_indicator_h: :regional_indicator_e::regional_indicator_o:',
        AnswerType.Trick,
    ],
    ['t`heo', AnswerType.Violation],
    ['bon ok tu peux écrire 1x théo sans suppr', AnswerType.Violation],

    [
        'https://images-ext-1.discordapp.net/external/2mxNq3mqCvSzBIOWlEe2QhrYEJ9slN0GfJJ3sJRR2vU/https/media.tenor.com/uBr8BS_BD5QAAAPo/theo-tweetpark.mp4',
        AnswerType.None,
    ],
    [
        'https://images-ext-1.discordapp.net/external/s09CM84U07rag6-int43u35SRCGU9qK2yuikd9uP_Ns/https/media.tenor.com/tq4Foo72P-MAAAPo/theo-theo-hernandez.mp4',
        AnswerType.None,
    ],
    [
        'théorie théo théorie théorie théorie théorie théorie théorie',
        AnswerType.Violation,
    ],
    ['téo', AnswerType.None],
    ['Téo se Téo surtout', AnswerType.None],
    ['Nostalgique ce teo', AnswerType.None],
    ['Ce soir raft pour ceux qui veulent nous rejoindre', AnswerType.None],
    ["Je l'utiliserai a un moment impromptu", AnswerType.None],
    ['Ton fond de webcam un vendredi', AnswerType.None],
    ['La corruption a été si facile', AnswerType.None],
    ['meurt pourriture communiste', AnswerType.None],
    [
        'https://images-ext-2.discordapp.net/external/I0VdJmPpO9VRfdbcbI4j2R1avelXLcxzFz6NqiPEnSg/https/media.tenor.com/meLXiGBtzXgAAAPo/incroyable.mp4',
        AnswerType.None,
    ],
    ["Mais tu vois mon gros théo c'est qu'une théorie", AnswerType.Violation],
    ['theheheheho', AnswerType.Violation],
    ['thhheo', AnswerType.Violation],
    ['théo', AnswerType.Violation],
    ['teo', AnswerType.None],
    ['Théo', AnswerType.Violation],
    ['the0', AnswerType.Violation],
    ['t.h.e.o', AnswerType.Violation],
    ['', AnswerType.None],
    [
        "Petite séance d'osthéopathie avec Mr. Bra de son prénom Ken",
        AnswerType.Correction,
    ],
];
